print("there are no changes done")
print("there are no changes done")
print("there are no changes done")
print("there are no changes done")
print("there are no changes done")
print("there are no changes done")
